// One-time provisioning of the 6 demo accounts (docs/12_seed_data_specification.md
// §2's persona table). Deliberately not an app feature -- docs/17_api_reference.md's
// route list has no registration endpoint, only POST /api/v1/auth/login, so
// account creation happens out-of-band, here, not through the running server.
// Connects with the Postgres *admin* credentials (root .env), not the
// restricted halcheck_app role -- that role only ever gets SELECT on users
// (db/init/002_app_role.sh), matching the principle that the running
// application should never be able to create its own logins.
import "dotenv/config";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import bcrypt from "bcryptjs";
import pg from "pg";

const here = dirname(fileURLToPath(import.meta.url));
const rootEnvPath = resolve(here, "../../.env");

function loadRootEnv(): Record<string, string> {
  const raw = readFileSync(rootEnvPath, "utf8");
  const env: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    env[trimmed.slice(0, idx)] = trimmed.slice(idx + 1);
  }
  return env;
}

const PERSONAS: Array<{
  role: string;
  personaName: string;
  fabricIdentity: string;
  username: string;
  // cid.GetID()'s real output for this identity -- captured live via
  // backend/scripts/capture-identity-cids.ts, not derived. null for
  // brand_owner, which has no write function and so never appears in a
  // submitted_by/added_by field on any chaincode response.
  fabricCid: string | null;
}> = [
  {
    role: "ingredient_qa", personaName: "Siti Rahayu", fabricIdentity: "ingredient-qa", username: "ingredient-qa",
    fabricCid: "eDUwOTo6Q049aW5ncmVkaWVudC1xYSxPVT1jbGllbnQsTz1IeXBlcmxlZGdlcixTVD1Ob3J0aCBDYXJvbGluYSxDPVVTOjpDTj1jYS5vcmcxLmV4YW1wbGUuY29tLE89b3JnMS5leGFtcGxlLmNvbSxMPUR1cmhhbSxTVD1Ob3J0aCBDYXJvbGluYSxDPVVT",
  },
  {
    role: "production_qa", personaName: "Budi Santoso", fabricIdentity: "production-qa", username: "production-qa",
    fabricCid: "eDUwOTo6Q049cHJvZHVjdGlvbi1xYSxPVT1jbGllbnQsTz1IeXBlcmxlZGdlcixTVD1Ob3J0aCBDYXJvbGluYSxDPVVTOjpDTj1jYS5vcmcxLmV4YW1wbGUuY29tLE89b3JnMS5leGFtcGxlLmNvbSxMPUR1cmhhbSxTVD1Ob3J0aCBDYXJvbGluYSxDPVVT",
  },
  {
    role: "compliance_officer", personaName: "Nurul Aisyah", fabricIdentity: "compliance-officer", username: "compliance-officer",
    fabricCid: "eDUwOTo6Q049Y29tcGxpYW5jZS1vZmZpY2VyLE9VPWNsaWVudCxPPUh5cGVybGVkZ2VyLFNUPU5vcnRoIENhcm9saW5hLEM9VVM6OkNOPWNhLm9yZzEuZXhhbXBsZS5jb20sTz1vcmcxLmV4YW1wbGUuY29tLEw9RHVyaGFtLFNUPU5vcnRoIENhcm9saW5hLEM9VVM=",
  },
  {
    role: "export_officer", personaName: "Farhan Hakim", fabricIdentity: "export-officer", username: "export-officer",
    fabricCid: "eDUwOTo6Q049ZXhwb3J0LW9mZmljZXIsT1U9Y2xpZW50LE89SHlwZXJsZWRnZXIsU1Q9Tm9ydGggQ2Fyb2xpbmEsQz1VUzo6Q049Y2Eub3JnMS5leGFtcGxlLmNvbSxPPW9yZzEuZXhhbXBsZS5jb20sTD1EdXJoYW0sU1Q9Tm9ydGggQ2Fyb2xpbmEsQz1VUw==",
  },
  { role: "brand_owner", personaName: "Brand Owner", fabricIdentity: "brand-owner", username: "brand-owner", fabricCid: null },
  {
    role: "system_admin", personaName: "Wayan Kusuma", fabricIdentity: "system-admin", username: "system-admin",
    fabricCid: "eDUwOTo6Q049c3lzdGVtLWFkbWluLE9VPWNsaWVudCxPPUh5cGVybGVkZ2VyLFNUPU5vcnRoIENhcm9saW5hLEM9VVM6OkNOPWNhLm9yZzEuZXhhbXBsZS5jb20sTz1vcmcxLmV4YW1wbGUuY29tLEw9RHVyaGFtLFNUPU5vcnRoIENhcm9saW5hLEM9VVM=",
  },
];

function randomPassword(): string {
  const bytes = new Uint8Array(18);
  crypto.getRandomValues(bytes);
  return Buffer.from(bytes).toString("base64url");
}

async function main() {
  const rootEnv = loadRootEnv();
  const client = new pg.Client({
    host: "localhost",
    port: 5432,
    user: rootEnv.POSTGRES_USER,
    password: rootEnv.POSTGRES_PASSWORD,
    database: rootEnv.POSTGRES_DB,
  });
  await client.connect();

  const credentials: string[] = [
    "# Generated by seed-users.ts -- gitignored, never commit.",
    "# One-time demo login credentials. Rotate before any tunnel activation (docs/15 §8).",
    "",
  ];

  try {
    for (const persona of PERSONAS) {
      const password = randomPassword();
      const passwordHash = await bcrypt.hash(password, 12);
      // Upsert, not a bare INSERT. As a bare INSERT this script could only
      // ever run once: re-running it failed on the users.username unique
      // constraint *before* writing the credentials file, so any environment
      // where the two drifted apart (found live on 2026-09-18: a rebuilt
      // network whose restored database held different passwords than the
      // credentials file on disk) had no documented way back -- every login
      // in the file was dead, and the fix was manual SQL. Re-running is now
      // the supported way to (re)provision or rotate the six demo logins;
      // rows keep their ids, so nothing that references them (idempotency
      // keys, audit rows) is orphaned.
      await client.query(
        `INSERT INTO users (username, password_hash, role, persona_name, fabric_identity, fabric_cid)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (username) DO UPDATE SET
           password_hash = EXCLUDED.password_hash,
           role = EXCLUDED.role,
           persona_name = EXCLUDED.persona_name,
           fabric_identity = EXCLUDED.fabric_identity,
           fabric_cid = EXCLUDED.fabric_cid`,
        [persona.username, passwordHash, persona.role, persona.personaName, persona.fabricIdentity, persona.fabricCid],
      );
      credentials.push(`${persona.role} (${persona.personaName}): username=${persona.username} password=${password}`);
      console.log(`seeded ${persona.username} (${persona.role})`);
    }
  } finally {
    await client.end();
  }

  const outPath = resolve(here, "../seeded-users.credentials.local");
  await import("node:fs/promises").then((fs) => fs.writeFile(outPath, credentials.join("\n") + "\n"));
  console.log(`\nCredentials written to ${outPath} (gitignored).`);
}

main().catch((err) => {
  console.error("seed-users failed:", err.message ?? err);
  process.exit(1);
});
